training:
  # 0.001
  learning_rate: 0.001
  epochs: 36
  # 128
  batch_size: 128
  patience: 25
  num_runs: 10
  eval_every: 2
  es_metric: ["Top1_Acc_Stream", "Loss_Stream"]

model:
  type: "CNN"
  layers: [64, 128, 256]
  num_classes: 10

dataset: 
  name: ["core50", "splitmnist", "splitcifar10"]
  fraction_to_take: 0.2
  validation_fraction: 0.2

scenario:
  type: ["nc", "ni"]
  mini: True
  object_lvl: False
  num_experiences: 10

wandb:
  project_name: "CL-Research-Training"
  entity: "Bard"

wandb_metrics_extraction:
  folder_name: "metrics_extraction"
  strategies: ["Cumulative", "RMN", "GR", "EWC", "GEM", "CWR*", "Naive"]
  group_names: ["splitcifar10_04-18-2024 19-30", "splitmnist_04-11-2024 18-31", "core50_ni_04-09-2024 03-35", "core50_nc_04-04-2024 22-58"]