training:
  learning_rate: 0.001
  epochs: 200
  batch_size: 128
  patience: 25
  num_runs: 5
  eval_every: 2
  es_metric: ["Top1_Acc_Stream", "Loss_Stream"]

model:
  type: "CNN"
  layers: [64, 128, 256]
  num_classes: 10

dataset: 
  name: ["core50", "splitmnist", "splitcifar10"]
  fraction_to_take: 0.2
  validation_fraction: 0.2

scenario:
  type: ["nc", "ni"]
  mini: True
  object_lvl: False
  num_experiences: 10

wandb:
  project_name: "CL-Research"
  entity: "Bard"

wandb_metrics_extraction:
  folder_name: "metrics_extraction"
  group_names: ["core50_nc_2024-01-26 21:28:24.151638", "core50_nc_2024-01-28 23:48:28.467730"]