training:
  learning_rate: 0.001
  epochs: 200
  batch_size: 128
  patience: 25
  num_runs: 2
  eval_every: 2
  es_metric: ["Top1_Acc_Stream", "Loss_Stream"]

model:
  type: "CNN"
  layers: [64, 128, 256]
  num_classes: 10

dataset: 
  name: ["core50", "splitmnist", "splitcifar10"]
  fraction_to_take: 0.2
  validation_fraction: 0.2

scenario:
  type: ["nc", "ni"]
  mini: True
  object_lvl: False
  num_experiences: 10

wandb:
  project_name: "CL-Research"
  entity: "Bard"

wandb_metrics_extraction:
  folder_name: "metrics_extraction"
  group_names: ["splitcifar10_02/03/2024, 05:13", "splitmnist_02/03/2024, 01:04", "core50_ni_02/02/2024, 15:44", "core50_nc_01/31/2024, 21:35"]