training:
  learning_rate: 0.001
  epochs: 10
  batch_size: 32
  patience: 25
  num_runs: 1
  eval_every: 2
  es_metric: ["Top1_Acc_Stream", "Loss_Stream"]

model:
  type: "CNN"
  layers: [64, 128, 256]
  num_classes: 10

dataset: 
  name: "core50"
  fraction_to_take: 0.2
  validation_fraction: 0.2

scenario:
  type: "nc"
  mini: True
  object_lvl: False

wandb:
  use_wandb: True
  project_name: "CL-Research"
  entity: "Bard"

project:
  name: ""
  group_name: ""